# Generated by Django 4.2 on 2025-03-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='id',
        ),
    ]
