# Generated by Django 4.2 on 2025-03-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userid_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('InterestID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
