# Generated by Django 4.2 on 2025-03-11 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('InterestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.interest')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UserID', 'InterestID')},
            },
        ),
    ]
