# Generated by Django 5.2 on 2025-06-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordreset",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="token",
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
