# Generated by Django 5.2 on 2025-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='publicID',
            new_name='public_id',
        ),
        migrations.RenameField(
            model_name='llmmodel',
            old_name='publicID',
            new_name='public_id',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='publicID',
            new_name='public_id',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='new conversation', max_length=255),
        ),
    ]
