# Generated by Django 5.2 on 2025-06-05 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_rename_publicid_conversation_public_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conversations.conversation",
                    ),
                ),
                (
                    "last_prompt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conversations.prompt",
                    ),
                ),
            ],
        ),
    ]
